config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :paths => 'users'

  root "posts#index"

  resources :friendships

  resources :users do
    resources :posts
    resources :friendships
  end

  # resources :friendships
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User", foreign_key: "friend_id"

  VALID_STATUSES = ['pending', 'accepted', 'declined']

  validates :friendship_status, inclusion: { in: VALID_STATUSES }
end

app/models/post.rb
class Post < ApplicationRecord
  resourcify

  has_many_attached :media
  belongs_to :user

  validates :body, presence: true, length: { minimum: 1 }

  def can_update?(updater)
    user == updater
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable

  has_many :posts, dependent: :destroy
  has_many :friendships, foreign_key: :user_id, class_name: "Friendship"
  has_many :friends, through: :friendships, source: :friend

  has_one_attached :avatar

  def full_name
    first_name + " " + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :update_allowed_parameters, if: :devise_controller?

    protected

    def update_allowed_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password, :avatar)}
    end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    before_action :authenticate_user!

    def index
        @filter = params[:filter]
        
        @user = current_user

        if @filter == "accepted"
            @friendships = Friendship.where('friendship_status = ? AND (user_id = ? OR friend_id = ?)', "accepted", @user.id, @user.id)
        end

        if @filter == "pending"
            @friendships = Friendship.where(user: @user, friendship_status: "pending")
        end 

        if @filter == "requests"
            @friendships = Friendship.where(friend: @user, friendship_status: "pending")
        end
    end

    def create
        puts "test"

        if friends?
            flash[:alert] = "Friends or request has been sent already"
            redirect_to(user_friendships_path(current_user, filter: :accepted)) && return
        end

        @friendship = Friendship.new(user: User.find(params[:friendship][:user]), friend: User.find(params[:friendship][:friend]), friendship_status: "pending" )

        if @friendship.save
            redirect_to root_path
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        @requester = User.find(params[:id])
        @user = User.find(params[:user_id])

        @pending_friendship = @requester.friendships.find_by(friend: @user, friendship_status: "pending");

        if @pending_friendship.update(friendship_status: params[:accept] ? "accepted" : "declined")
            redirect_to root_path
        else
            render :index, status: :unprocessable_entity
        end
    end

    private
        def friendship_params
            params.require(:friendship).permit(:user, :friend, :friendship_status)
        end

        def friends?
            friendships = Friendship.where('user_id = ? OR friend_id = ?', params[:friendship][:user], params[:friendship][:user])

            friendships.each do | friendship |
                if friendship.friend_id == params[:friendship][:friend].to_i || friendship.user_id == params[:friendship][:friend].to_i
                    return true
                end
            end

            return false
        end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!

    def index
        @user = current_user
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @user = current_user
    end

    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])

        unless @post.can_update?(@post.user)
            flash.now[:alert] = "Unable to update Post"
            return render :edit, status: :unprocessable_entity
        end

        if @post.update(post_params)
            redirect_to user_post_path(@post.user, @post)
        else
            flash.now[:alert] = "Unable to update Post"
            render :edit, status: :unprocessable_entity
        end
    end

    def create
        @user = current_user

        @post = @user.posts.create(post_params)

        if @post["id"]
            redirect_to user_posts_path(@user)
        else
            flash.now[:alert] = "Unable to create Post"
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        @user = current_user
        @post = @user.posts.find(params[:id])

        unless @post.can_update?(@user)
            flash.now[:alert] = "Unable to delete Post"
            return render :index, status: :unprocessable_entity
        end

        @post.destroy
        redirect_to user_posts_path(@user), status: :see_other
    end

    private
        def post_params
            params.require(:post).permit(:body, media: [])
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @friendship = Friendship.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/index.html.erb
<ul class="nav nav-tabs my-3">
  <li class="nav-item">
    <%= link_to "Friends list", user_friendships_path(current_user, filter: :accepted), class: @filter == "accepted" ? "nav-link active" : "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Requests sent", user_friendships_path(current_user, filter: :pending), class: @filter == "pending" ? "nav-link active" : "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "Friend requests", user_friendships_path(current_user, filter: :requests), class: @filter == "requests" ? "nav-link active" : "nav-link" %>
  </li>
</ul>

<% if @filter == "accepted" %>
  <% @friendships.each do | friendship | %>
    <% if friendship.user == current_user %>
      <div class="card mb-3 mx-3">
        <div class="d-flex flex-column card-body">
            <div class="d-flex justify-content-start align-items-center">
                <% if friendship.friend.avatar.attached? %>
                    <%= image_tag friendship.friend.avatar.variant(resize: "50x50"), class: "rounded-circle me-2" %>
                <% end %>
                <%= friendship.friend.full_name %>
              </div>
          </div>
      </div>    
    <% else %>
      <div class="card mb-3 mx-3">
        <div class="d-flex flex-column card-body">
            <div class="d-flex justify-content-start align-items-center">
                <% if friendship.user.avatar.attached? %>
                    <%= image_tag friendship.user.avatar.variant(resize: "50x50"), class: "rounded-circle me-2" %>
                <% end %>
                <%= friendship.user.full_name %>
              </div>
          </div>
      </div> 
    <% end %>
  <% end %>
<% else %>
  <% @friendships.each do | friendship | %>
    <div class="card mb-3 mx-3">
      <div class="d-flex flex-row card-body">
        <div class="d-flex justify-content-start align-items-center" style="flex: 1;">
            <% if @filter == "pending" %>
              <% if friendship.friend.avatar.attached? %>
                <%= image_tag friendship.friend.avatar.variant(resize: "50x50"), class: "rounded-circle me-2" %>
              <% end %>
              <%= friendship.friend.full_name %>
            <% else %>
              <% if friendship.user.avatar.attached? %>
                <%= image_tag friendship.user.avatar.variant(resize: "50x50"), class: "rounded-circle me-2" %>
              <% end %>
              <%= friendship.user.full_name %>
            <% end %>
        </div>
        <% if @filter == "requests" %>
          <div class="d-flex justify-content-end align-items-center" style="flex: 1;">
              <%= link_to "Accept", user_friendship_path(friendship.friend, friendship.user, accept: true), class: "btn btn-dark me-1", data: {
                          turbo_method: :put,
                          turbo_confirm: "Accept friend request?"
                        } %>

              <%= link_to "Decline", user_friendship_path(friendship.friend, friendship.user, accept: false), class: "btn btn-outline-dark", data: {
                          turbo_method: :put,
                          turbo_confirm: "Decline friend request?"
                        } %>
          </div>
        <% end %>
      </div>
    </div>    
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Socmed</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", user_friendships_path(current_user, filter: :accepted), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "People on Socmed", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
            </li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path, data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure you want to sign out?"
                    }, class: "dropdown-item" %>
            </li>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socmed</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <main class="container-fluid p-0">
      <% if notice %>
        <p class="alert alert-info mt-3 mx-3"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger mt-3 mx-3"><%= alert %></p>
      <% end %>
      
      <% if user_signed_in? %>
        <%= render 'layouts/navbar' %>
      <%end%>

      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: user_post do |form| %>
  <div class="mb-3">
    <%= form.label :body, class: "form-label" %><br>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.file_field :media, multiple: true %> 
  </div>

  <div>
    <%= form.submit "Submit", class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/posts/_image_modal.html.erb
<div class="modal fade" id="exampleModal-<%= index %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-xl">
        <div class="modal-content">
        <div class="modal-header">
            <h5><%= %></h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
                <img src="<%= (url_for(media))%>" class="img-fluid">
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
</div>

app/views/posts/_post.html.erb
<div class="card mb-3">
  <div class="d-flex card-header justify-content-between">
    <div class="d-flex justify-content-start align-items-center">
        <% if post.user.avatar.attached? %>
            <%= image_tag post.user.avatar.variant(resize: "20x20"), class: "rounded-circle me-2"%>
        <% end %>
        <%= post.user.full_name %>
    </div>
    <div>
        <%= link_to "", user_post_path(post.user, post), class: "btn-close", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
    </div>
  </div>
  <div class="d-flex flex-column card-body">
    <p class="card-text"><%= post.body %></p>
    <% if post.media.attached? %>
        <div class="d-flex flex-wrap flex-row">
            <% post.media.each_with_index do |media, index| %>
                    <p class="flex-shrink-0 img-thumbnail rounded position-relative m-1 ms-0">
                        <button type="button" class="btn btn-secondary position-absolute top-50 start-50 translate-middle" style="opacity: 0.6;" data-bs-toggle="modal" data-bs-target="#exampleModal-<%= index %>">
                            View
                        </button>

                        <%= image_tag media.variant(resize: "200x200")%>
                    </p>

                <%= render "image_modal", media: media, index: index %>
            <% end%>
        </div>
    <% end %>
    <%= link_to "Open Post", [post.user, post], class: "btn btn-outline-primary" %>
  </div>
</div>    

app/views/posts/edit.html.erb
<div class="d-flex flex-column p-5" style="flex: 1;">
    <h1>Edit Post</h1>

    <%= render "form", user_post: [@post.user, @post] %>
</div>

app/views/posts/index.html.erb
<div class="d-flex flex-column p-3">
    <%= link_to "New Post", new_user_post_path(@user), class: "btn btn-outline-primary col my-3" %>

    <%= render @user.posts %>
</div>

app/views/posts/new.html.erb
<div class="d-flex flex-column p-5" style="flex: 1;">
    <h2>Create Post</h2>

    <%= render 'form', user_post: [@user, @user.posts.build] %>
</div>

app/views/posts/show.html.erb
<div class="d-flex flex-column p-5">

  <div class="d-flex card-header justify-content-between mb-3">
    <div class="d-flex justify-content-start align-items-center">
        <% if @post.user.avatar.attached? %>
            <%= image_tag @post.user.avatar.variant(resize: "50x50"), class: "rounded-circle me-2"%>
        <% end %>
        <h3><%= @post.user.full_name %></h3>
    </div>
    <div>
        <%= link_to "Edit", edit_user_post_path(@post.user, @post), class: "btn btn-outline-dark me-1" %>

        <%= link_to "Delete", user_post_path(@post.user, @post), class: "btn btn-dark", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
    </div>
  </div>
  <p class="bg-secondary w-100" style="height: 1px;"></p>

  <p><%= @post.body %></p>

  <% if @post.media.attached? %>
    <% @post.media.each_with_index do |media, index| %>
        <%= image_tag media, class: "d-block w-100" %>
    <% end%>
  <% end %>
</div>

app/views/users/_user.html.erb
<% unless user == current_user %>
    <div class="card mb-3">
        <div class="d-flex flex-column card-body">
            <div class="d-flex justify-content-start align-items-center mb-3">
                <% if user.avatar.attached? %>
                    <%= image_tag user.avatar.variant(resize: "50x50"), class: "rounded-circle me-2"%>
                <% end %>
                <%= user.full_name %>
            </div>

            <%= form_with model: @friendship, data: { turbo_confirm: "Add " + user.full_name + " as friend?" } do |form| %>
                <p>
                    <%= form.hidden_field :user, value: current_user.id %>
                </p>

                <p>
                    <%= form.hidden_field :friend, value: user.id %>
                </p>

                <p>
                    <%= form.hidden_field :friendship_status, value: "pending" %>
                </p>

                <p>
                    <%= form.submit "Add friend", class: "btn btn-outline-primary" %>
                </p>
            <% end %>
        </div>
    </div>    
<%end%>

app/views/users/index.html.erb
<div class="d-flex flex-column p-3">
    <%= render @users %>
</div>